# Generated by Django 3.2.8 on 2021-12-03 07:07

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20, unique=True, validators=[users.validators.UsernameValidator()], verbose_name='Username'),
        ),
    ]
