# Generated by Django 3.2.8 on 2021-12-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userdetailsstatic_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetailsstatic',
            name='activity_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userdetailsstatic',
            name='profile_icon',
            field=models.IntegerField(default=0),
        ),
    ]
