# Generated by Django 3.2.8 on 2021-12-06 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211205_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userphysicaldata',
            name='date',
        ),
        migrations.AddField(
            model_name='userphysicaldata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at'),
        ),
        migrations.AddField(
            model_name='userphysicaldata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at'),
        ),
    ]
