# Generated by Django 3.2.8 on 2021-12-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_userphysicaldata_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userphysicaldata',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
