# Generated by Django 3.2.8 on 2021-12-15 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_alter_post_type'),
        ('users', '0007_userphysicaldata_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userslikedposts',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='community.post'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userslikedposts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userslikedqnaposts',
            name='qna_post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='community.qna'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userslikedqnaposts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userssavedqnaposts',
            name='qna_post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='community.qna'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UsersLikedQnaAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qna_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.qnaanswer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_liked_qna_answers',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UsersLikedQnaAnswerComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qna_answer_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.qnaanswercomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_liked_qna_answer_comments',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UsersLikedQnaAnswerCommentReplies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qna_answer_comment_reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.qnaanswercommentreply')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_liked_qna_answer_comment_replies',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UsersLikedPostComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.postcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_liked_post_comments',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UsersLikedPostCommentReplies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_comment_reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.postcommentreply')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_liked_post_comment_replies',
                'managed': True,
            },
        ),
    ]
