# Generated by Django 3.2.8 on 2021-12-22 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0011_rename_count_total_comments_qnacount_count_comments'),
        ('users', '0009_auto_20211220_2103'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UsersLikedQnaPosts',
            new_name='UsersLikedQnas',
        ),
        migrations.RenameModel(
            old_name='UsersSavedQnaPosts',
            new_name='UsersSavedQnas',
        ),
        migrations.RenameField(
            model_name='userslikedqnas',
            old_name='qna_post',
            new_name='qna',
        ),
        migrations.RenameField(
            model_name='userssavedqnas',
            old_name='qna_post',
            new_name='qna',
        ),
        migrations.AlterModelTable(
            name='userslikedqnas',
            table='users_liked_qnas',
        ),
        migrations.AlterModelTable(
            name='userssavedqnas',
            table='users_saved_qnas',
        ),
    ]
