# Generated by Django 3.2.8 on 2021-12-23 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_delete_userslikedqnas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsersLikedQnaAnswerCommentReplies',
        ),
    ]
