# Generated by Django 3.2.8 on 2022-01-20 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_delete_userslikedqnaanswercommentreplies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetailsstatic',
            name='profile_icon',
        ),
    ]
