# Generated by Django 3.2.8 on 2022-02-05 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_userdetailsstatic_profile_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetailscount',
            name='count_protein',
            field=models.IntegerField(default=0),
        ),
    ]
