# Generated by Django 3.2.8 on 2022-02-06 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_userdetailscount_count_protein'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPhysicalData',
        ),
    ]
