# Generated by Django 3.2.8 on 2022-02-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_delete_userphysicaldata'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetailsstatic',
            name='height',
            field=models.FloatField(null=True),
        ),
    ]
