# Generated by Django 3.2.8 on 2022-02-15 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_userdetailsstatic_height'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetailscount',
            old_name='count_uploaded_qna_posts',
            new_name='count_uploaded_qnas',
        ),
    ]
