# Generated by Django 3.2.8 on 2022-02-15 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_rename_count_uploaded_qna_posts_userdetailscount_count_uploaded_qnas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetailscount',
            name='count_liked_posts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userdetailscount',
            name='count_saved_posts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userdetailscount',
            name='count_uploaded_posts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userdetailscount',
            name='count_uploaded_qnas',
            field=models.IntegerField(default=0),
        ),
    ]
