# Generated by Django 3.2.8 on 2022-02-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20220215_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetailscount',
            name='count_uploaded_answers',
            field=models.IntegerField(default=0),
        ),
    ]
