# Generated by Django 3.2.8 on 2022-02-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_userdetailscount_count_uploaded_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetailscount',
            name='answer_acception_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userdetailscount',
            name='count_accepted_answers',
            field=models.IntegerField(default=0),
        ),
    ]
