# Generated by Django 3.2.8 on 2022-02-16 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20220215_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetailsstatic',
            name='profile_community_privacy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdetailsstatic',
            name='profile_physical_data_privacy',
            field=models.BooleanField(default=False),
        ),
    ]
