# Generated by Django 3.2.8 on 2022-04-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20220226_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetailsstatic',
            name='fcm_token',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
