# Generated by Django 3.2.8 on 2022-04-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_user_auth_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='auth_provider',
        ),
        migrations.AddField(
            model_name='userdetailsstatic',
            name='auth_provider',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
