# Generated by Django 3.2.8 on 2022-04-16 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20220415_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetailsstatic',
            name='profile_community_privacy',
        ),
        migrations.RemoveField(
            model_name='userdetailsstatic',
            name='profile_physical_data_privacy',
        ),
        migrations.AddField(
            model_name='userdetailsstatic',
            name='profile_privacy',
            field=models.IntegerField(default=0),
        ),
    ]
