# Generated by Django 3.2.8 on 2022-05-09 11:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20220416_0610'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blocked_users',
            field=models.ManyToManyField(blank=True, related_name='_users_user_blocked_users_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='reported_users',
            field=models.ManyToManyField(blank=True, related_name='_users_user_reported_users_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userdetailscount',
            name='count_reports',
            field=models.IntegerField(default=0),
        ),
    ]
