# Generated by Django 3.2.8 on 2022-05-09 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20220509_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='blocked_users',
        ),
        migrations.RemoveField(
            model_name='user',
            name='reported_users',
        ),
        migrations.CreateModel(
            name='UsersReportedUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_reported_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_reported_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_reported_users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UsersBlockedUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_blocked_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_blocked_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_blocked_users',
                'managed': True,
            },
        ),
    ]
