# Generated by Django 3.2.8 on 2022-05-13 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20220509_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetailsstatic',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='userdetailsstatic',
            name='gender',
            field=models.IntegerField(null=True),
        ),
    ]
