# Generated by Django 3.2.8 on 2022-01-21 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyExerciseStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_exercise_time', models.IntegerField(default=0)),
                ('total_sets', models.IntegerField(default=0)),
                ('max_one_rm', models.FloatField(default=0)),
                ('total_volume', models.FloatField(default=0)),
                ('total_distance', models.FloatField(default=0)),
                ('day', models.DateField(auto_now_add=True)),
                ('memo', models.CharField(max_length=300, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'daily_exercise_stats',
                'managed': True,
            },
        ),
    ]
