# Generated by Django 3.2.8 on 2022-02-09 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_auto_20220209_2300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='physicaldatarecord',
            old_name='inBodyScore',
            new_name='inbody_score',
        ),
    ]
