# Generated by Django 3.2.8 on 2022-02-09 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_rename_inbodyscore_physicaldatarecord_inbody_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicaldatarecord',
            name='bmi',
            field=models.FloatField(default=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='physicaldatarecord',
            name='weight',
            field=models.FloatField(default=70),
            preserve_default=False,
        ),
    ]
