# Generated by Django 3.2.8 on 2022-02-18 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0007_dailyexercisestats_total_reps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyexercisestats',
            name='total_reps',
        ),
    ]
