# Generated by Django 3.2.8 on 2021-12-01 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField()),
                ('title', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=500)),
                ('modified', models.BooleanField()),
            ],
            options={
                'db_table': 'post',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('creation_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'post_comment',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PostCommentCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_likes', models.IntegerField()),
                ('count_reports', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'post_comment_count',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PostCommentReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('creation_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'post_comment_reply',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PostCommentReplyCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_likes', models.IntegerField()),
                ('count_reports', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'post_comment_reply_count',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PostCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField()),
                ('count_likes', models.IntegerField()),
                ('count_comments', models.IntegerField()),
                ('count_saved', models.IntegerField()),
                ('count_reports', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'post_count',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Qna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=500)),
                ('creation_date', models.DateTimeField()),
                ('modified', models.BooleanField()),
                ('solved', models.BooleanField()),
                ('type', models.IntegerField()),
            ],
            options={
                'db_table': 'qna_post',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='QnaAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('creation_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'qna_post_answer',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='QnaAnswerComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('creation_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'qna_post_answer_comment',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='QnaAnswerCommentReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('creation_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'qna_post_answer_comment_reply',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='QnaAnswerCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_likes', models.IntegerField()),
                ('count_comments', models.IntegerField()),
                ('count_reports', models.IntegerField()),
            ],
            options={
                'db_table': 'qna_post_answer_count',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='QnaCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField()),
                ('count_total_likes', models.IntegerField()),
                ('count_answers', models.IntegerField()),
                ('count_saved', models.IntegerField()),
                ('count_total_comments', models.IntegerField()),
                ('count_reports', models.IntegerField()),
            ],
            options={
                'db_table': 'qna_post_count',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='QnaPreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('creation_date', models.DateTimeField()),
                ('solved', models.BooleanField()),
                ('type', models.IntegerField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='community.qna')),
            ],
            options={
                'db_table': 'qna_post_preview',
                'managed': True,
            },
        ),
    ]
