# Generated by Django 3.2.8 on 2021-10-18 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField()),
                ('title', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=500)),
                ('modified', models.IntegerField()),
            ],
            options={
                'db_table': 'post',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('creation_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'post_comment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PostCommentCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_likes', models.IntegerField()),
                ('count_reports', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'post_comment_count',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PostCommentReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('creation_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'post_comment_reply',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PostCommentReplyCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_likes', models.IntegerField()),
                ('count_reports', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'post_comment_reply_count',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PostCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_likes', models.IntegerField()),
                ('count_comments', models.IntegerField()),
                ('count_saved', models.IntegerField()),
                ('count_reports', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'post_count',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QnaPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=500)),
                ('creation_date', models.DateTimeField()),
                ('modified', models.IntegerField()),
                ('solved', models.IntegerField()),
                ('type', models.IntegerField()),
            ],
            options={
                'db_table': 'qna_post',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QnaPostAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('creation_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'qna_post_answer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QnaPostAnswerComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'qna_post_answer_comment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QnaPostAnswerCommentReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'qna_post_answer_comment_reply',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QnaPostAnswerCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_likes', models.IntegerField()),
                ('count_comments', models.IntegerField()),
                ('count_reports', models.IntegerField()),
            ],
            options={
                'db_table': 'qna_post_answer_count',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QnaPostCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_total_likes', models.IntegerField()),
                ('count_answers', models.IntegerField()),
                ('count_saved', models.IntegerField()),
                ('count_total_comments', models.IntegerField()),
                ('count_reports', models.IntegerField()),
            ],
            options={
                'db_table': 'qna_post_count',
                'managed': False,
            },
        ),
    ]
