# Generated by Django 3.2.8 on 2021-12-01 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='qnapreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qnacount',
            name='qna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='community.qna'),
        ),
        migrations.AddField(
            model_name='qnaanswercount',
            name='qna_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='community.qnaanswer'),
        ),
        migrations.AddField(
            model_name='qnaanswercommentreply',
            name='qna_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='community.qnaanswer'),
        ),
        migrations.AddField(
            model_name='qnaanswercommentreply',
            name='qna_answer_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='community.qnaanswercomment'),
        ),
        migrations.AddField(
            model_name='qnaanswercommentreply',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qnaanswercomment',
            name='qna_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='community.qnaanswer'),
        ),
        migrations.AddField(
            model_name='qnaanswercomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qnaanswer',
            name='qna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='community.qna'),
        ),
        migrations.AddField(
            model_name='qnaanswer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qna',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postcount',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='community.post'),
        ),
        migrations.AddField(
            model_name='postcommentreplycount',
            name='post_comment_reply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='community.postcommentreply'),
        ),
        migrations.AddField(
            model_name='postcommentreply',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='community.post'),
        ),
        migrations.AddField(
            model_name='postcommentreply',
            name='post_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='community.postcomment'),
        ),
        migrations.AddField(
            model_name='postcommentreply',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postcommentcount',
            name='post_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='community.postcomment'),
        ),
        migrations.AddField(
            model_name='postcomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.post'),
        ),
        migrations.AddField(
            model_name='postcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
