# Generated by Django 3.2.8 on 2021-12-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_auto_20211202_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='postcommentcount',
            name='count_likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='postcommentcount',
            name='count_reports',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='postcommentreply',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='postcommentreplycount',
            name='count_likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='postcommentreplycount',
            name='count_reports',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='postcount',
            name='count_comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='postcount',
            name='count_reports',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='postcount',
            name='count_saved',
            field=models.IntegerField(default=0),
        ),
    ]
