# Generated by Django 3.2.8 on 2021-12-20 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0006_usersreportedpostcommentreplies_usersreportedpostcomments_usersreportedposts_usersreportedqnaanswerc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcommentcount',
            name='post_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.postcomment'),
        ),
        migrations.AlterField(
            model_name='postcommentreply',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.post'),
        ),
        migrations.AlterField(
            model_name='postcommentreply',
            name='post_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.postcomment'),
        ),
        migrations.AlterField(
            model_name='postcommentreply',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postcommentreplycount',
            name='post_comment_reply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.postcommentreply'),
        ),
    ]
