# Generated by Django 3.2.8 on 2021-12-21 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_rename_count_total_likes_qnacount_count_likes'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='qna',
            table='qna',
        ),
        migrations.AlterModelTable(
            name='qnaanswer',
            table='qna_answer',
        ),
        migrations.AlterModelTable(
            name='qnaanswercomment',
            table='qna_answer_comment',
        ),
        migrations.AlterModelTable(
            name='qnaanswercommentreply',
            table='qna_answer_comment_reply',
        ),
        migrations.AlterModelTable(
            name='qnaanswercount',
            table='qna_answer_count',
        ),
        migrations.AlterModelTable(
            name='qnacount',
            table='qna_count',
        ),
        migrations.AlterModelTable(
            name='qnapreview',
            table='qna_preview',
        ),
    ]
