# Generated by Django 3.2.8 on 2021-12-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0009_auto_20211221_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qna',
            name='type',
            field=models.IntegerField(default=1),
        ),
    ]
