# Generated by Django 3.2.8 on 2021-12-23 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0011_rename_count_total_comments_qnacount_count_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='QnaAnswerCommentCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_likes', models.IntegerField()),
                ('count_reports', models.IntegerField()),
                ('qna_answer_comment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='community.qnaanswercomment')),
            ],
            options={
                'db_table': 'qna_answer_comment_count',
                'managed': True,
            },
        ),
    ]
