# Generated by Django 3.2.8 on 2021-12-23 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0012_qnaanswercommentcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qnaanswer',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='qnaanswercomment',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='qnaanswercommentreply',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
