# Generated by Django 3.2.8 on 2022-02-25 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0017_remove_qna_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='qnaanswer',
            name='selectedType',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='QnaPreview',
        ),
    ]
