# Generated by Django 3.2.8 on 2022-03-16 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0019_alter_qna_solved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qnaanswer',
            old_name='selectedType',
            new_name='selected_type',
        ),
    ]
