# Generated by Django 3.2.8 on 2022-03-17 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0020_rename_selectedtype_qnaanswer_selected_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='QnaAnswerCommentReplyCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_reports', models.IntegerField()),
                ('qna_answer_comment_reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.qnaanswercommentreply')),
            ],
            options={
                'db_table': 'qna_answer_comment_reply_count',
                'managed': True,
            },
        ),
    ]
