# Generated by Django 3.2.8 on 2022-04-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0023_auto_20220404_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='qna',
            name='hot',
            field=models.BooleanField(default=False),
        ),
    ]
