# Generated by Django 3.2.8 on 2021-12-01 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercise', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciserecordweight',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exerciserecordaerobicrest',
            name='exercise_record_aerobic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exercise.exerciserecordaerobic'),
        ),
        migrations.AddField(
            model_name='exerciserecordaerobic',
            name='exercise_plan_aerobic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exercise.exerciseplanaerobic'),
        ),
        migrations.AddField(
            model_name='exerciserecordaerobic',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exerciseplanweightset',
            name='exercise_plan_weight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exercise.exerciseplanweight'),
        ),
        migrations.AddField(
            model_name='exerciseplanweight',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exercise.exercise'),
        ),
        migrations.AddField(
            model_name='exerciseplanweight',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exerciseplanaerobic',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exercise.exercise'),
        ),
        migrations.AddField(
            model_name='exerciseplanaerobic',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exercisedetails',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exercise.exercise'),
        ),
    ]
