# Generated by Django 3.2.8 on 2021-12-10 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='difficulty',
        ),
    ]
