# Generated by Django 3.2.8 on 2021-10-26 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0002_auto_20211018_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExercisePlanWeightSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_num', models.IntegerField()),
                ('target_weight', models.FloatField()),
                ('target_reps', models.IntegerField()),
            ],
            options={
                'db_table': 'exercise_plan_weight_set',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='ExcercisePlanWeightSet',
        ),
    ]
