# Generated by Django 3.2.8 on 2021-12-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0004_alter_exercise_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseplanweight',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
