# Generated by Django 3.2.8 on 2022-01-19 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercise', '0005_alter_exerciseplanweight_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisedetails',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.exercise'),
        ),
        migrations.AlterField(
            model_name='exerciseplanaerobic',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.exercise'),
        ),
        migrations.AlterField(
            model_name='exerciseplanaerobic',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exerciseplanweight',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.exercise'),
        ),
        migrations.AlterField(
            model_name='exerciseplanweight',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exerciseplanweightset',
            name='exercise_plan_weight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.exerciseplanweight'),
        ),
        migrations.AlterField(
            model_name='exerciserecordaerobic',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='exerciserecordaerobic',
            name='exercise_plan_aerobic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.exerciseplanaerobic'),
        ),
        migrations.AlterField(
            model_name='exerciserecordaerobic',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exerciserecordaerobicrest',
            name='exercise_record_aerobic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.exerciserecordaerobic'),
        ),
        migrations.AlterField(
            model_name='exerciserecordweight',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='exerciserecordweight',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.exercise'),
        ),
        migrations.AlterField(
            model_name='exerciserecordweight',
            name='exercise_plan_weight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.exerciseplanweight'),
        ),
        migrations.AlterField(
            model_name='exerciserecordweight',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exerciserecordweightset',
            name='exercise_record_weight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.exerciserecordweight'),
        ),
    ]
