# Generated by Django 3.2.8 on 2022-01-20 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0006_auto_20220119_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciserecordweight',
            name='max_one_rm',
            field=models.FloatField(default=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exerciserecordweight',
            name='total_volume',
            field=models.FloatField(default=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exerciserecordweightset',
            name='one_rm',
            field=models.FloatField(default=60),
            preserve_default=False,
        ),
    ]
