# Generated by Django 3.2.8 on 2022-01-21 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercise', '0008_auto_20220120_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyExerciseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_exercise_time', models.IntegerField(null=True)),
                ('total_sets', models.IntegerField(default=0)),
                ('max_one_rm', models.FloatField(default=0)),
                ('total_volume', models.FloatField(default=0)),
                ('total_distance', models.FloatField(default=0)),
                ('day', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
