# Generated by Django 3.2.8 on 2022-01-21 17:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercise', '0010_dailyexerciserecord_memo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DailyExerciseRecord',
            new_name='DailyExerciseStats',
        ),
        migrations.AlterModelOptions(
            name='dailyexercisestats',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='dailyexercisestats',
            table='daily_exercise_stats',
        ),
    ]
