# Generated by Django 3.2.8 on 2022-01-21 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0011_auto_20220121_1725'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyExerciseStats',
        ),
    ]
