# Generated by Django 3.2.8 on 2022-01-21 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0012_delete_dailyexercisestats'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciserecordweight',
            name='exercise_time',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
