# Generated by Django 3.2.8 on 2022-01-23 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0013_exerciserecordweight_exercise_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciserecordaerobicrest',
            name='exercise_record_aerobic',
        ),
        migrations.DeleteModel(
            name='ExerciseRecordAerobic',
        ),
        migrations.DeleteModel(
            name='ExerciseRecordAerobicRest',
        ),
    ]
