# Generated by Django 3.2.8 on 2022-01-23 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercise', '0014_auto_20220123_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseRecordAerobic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_distance', models.FloatField()),
                ('record_duration', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.exercise')),
                ('exercise_plan_aerobic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.exerciseplanaerobic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'exercise_record_aerobic',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ExerciseRecordAerobicRest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.IntegerField()),
                ('end_time', models.IntegerField(blank=True, null=True)),
                ('exercise_record_aerobic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.exerciserecordaerobic')),
            ],
            options={
                'db_table': 'exercise_record_aerobic_rest',
                'managed': True,
            },
        ),
    ]
