# Generated by Django 3.2.8 on 2022-01-25 22:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercise', '0015_exerciserecordaerobic_exerciserecordaerobicrest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExercisePlanAerobic',
            new_name='ExercisePlanCardio',
        ),
        migrations.RenameModel(
            old_name='ExerciseRecordAerobic',
            new_name='ExerciseRecordCardio',
        ),
        migrations.RenameModel(
            old_name='ExerciseRecordAerobicRest',
            new_name='ExerciseRecordCardioRest',
        ),
        migrations.RenameField(
            model_name='exerciserecordcardio',
            old_name='exercise_plan_aerobic',
            new_name='exercise_plan_cardio',
        ),
        migrations.RenameField(
            model_name='exerciserecordcardiorest',
            old_name='exercise_record_aerobic',
            new_name='exercise_record_cardio',
        ),
        migrations.AddField(
            model_name='exercise',
            name='type',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercise',
            name='target_muscle',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterModelTable(
            name='exerciseplancardio',
            table='exercise_plan_cardio',
        ),
        migrations.AlterModelTable(
            name='exerciserecordcardio',
            table='exercise_record_cardio',
        ),
        migrations.AlterModelTable(
            name='exerciserecordcardiorest',
            table='exercise_record_cardio_rest',
        ),
    ]
