# Generated by Django 3.2.8 on 2022-02-18 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0016_auto_20220125_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciserecordcardio',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='exerciserecordcardio',
            name='exercise_plan_cardio',
        ),
        migrations.RemoveField(
            model_name='exerciserecordcardio',
            name='user',
        ),
        migrations.RemoveField(
            model_name='exerciserecordcardiorest',
            name='exercise_record_cardio',
        ),
        migrations.DeleteModel(
            name='ExercisePlanCardio',
        ),
        migrations.DeleteModel(
            name='ExerciseRecordCardio',
        ),
        migrations.DeleteModel(
            name='ExerciseRecordCardioRest',
        ),
    ]
