# Generated by Django 3.2.8 on 2022-02-18 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercise', '0017_auto_20220218_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExercisePlanCardio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('target_distance', models.FloatField(null=True)),
                ('target_duration', models.TimeField(null=True)),
                ('completed', models.BooleanField(default=False)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'exercise_plan_cardio',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ExerciseRecordCardio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_distance', models.FloatField()),
                ('record_duration', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.exercise')),
                ('exercise_plan_cardio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.exerciseplancardio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'exercise_record_cardio',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ExerciseRecordCardioRest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.IntegerField()),
                ('end_time', models.IntegerField(blank=True, null=True)),
                ('exercise_record_cardio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.exerciserecordcardio')),
            ],
            options={
                'db_table': 'exercise_record_cardio_rest',
                'managed': True,
            },
        ),
        migrations.AddConstraint(
            model_name='exerciseplancardio',
            constraint=models.CheckConstraint(check=models.Q(('target_distance__isnull', False), ('target_duration__isnull', False), _connector='OR'), name='not_both_null'),
        ),
    ]
