# Generated by Django 3.2.8 on 2022-02-18 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0019_alter_exerciseplancardio_target_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciserecordweight',
            name='total_reps',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
    ]
