# Generated by Django 3.2.8 on 2022-02-19 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0020_exerciserecordweight_total_reps'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExerciseRecordCardioRest',
        ),
    ]
