# Generated by Django 3.2.8 on 2022-02-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0021_delete_exerciserecordcardiorest'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='cardio_met',
            field=models.FloatField(null=True),
        ),
    ]
