# Generated by Django 3.2.8 on 2022-02-19 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0022_exercise_cardio_met'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciserecordcardio',
            name='record_distance',
            field=models.FloatField(null=True),
        ),
    ]
