# Generated by Django 3.2.8 on 2022-02-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0024_alter_exerciserecordcardio_record_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciserecordcardio',
            name='calories',
            field=models.FloatField(null=True),
        ),
    ]
