# Generated by Django 3.2.8 on 2022-02-20 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0025_exerciserecordcardio_calories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exerciserecordcardio',
            old_name='calories',
            new_name='record_calories',
        ),
    ]
