# Generated by Django 3.2.8 on 2022-02-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0026_rename_calories_exerciserecordcardio_record_calories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciserecordcardio',
            name='record_calories',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
