# Generated by Django 3.2.8 on 2022-02-23 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0027_alter_exerciserecordcardio_record_calories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciserecordweightset',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='exerciserecordweightset',
            name='start_time',
        ),
    ]
