# Generated by Django 3.2.8 on 2022-05-09 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0028_auto_20220223_2207'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exerciseplancardio',
            options={'get_latest_by': 'date', 'managed': True},
        ),
        migrations.AlterModelOptions(
            name='exerciseplanweight',
            options={'get_latest_by': 'date', 'managed': True},
        ),
    ]
