# Generated by Django 3.2.8 on 2022-04-06 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='link',
            new_name='link_id',
        ),
    ]
