# Generated by Django 3.2.8 on 2022-04-16 23:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0002_rename_link_notification_link_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotiReception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exerciseAttendanceNoti', models.BooleanField(default=True)),
                ('dailyExerciseCompleteNoti', models.BooleanField(default=True)),
                ('weeklyExerciseProteinNoti', models.BooleanField(default=True)),
                ('hotPostNoti', models.BooleanField(default=True)),
                ('hotQnaNoti', models.BooleanField(default=True)),
                ('qnaBestAnswerNoti', models.BooleanField(default=True)),
                ('qnaSelectedAnswerNoti', models.BooleanField(default=True)),
                ('activityLevelUpNoti', models.BooleanField(default=True)),
                ('postCommentNoti', models.BooleanField(default=True)),
                ('postReplyNoti', models.BooleanField(default=True)),
                ('qnaAnswerNoti', models.BooleanField(default=True)),
                ('qnaCommentNoti', models.BooleanField(default=True)),
                ('qnaReplyNoti', models.BooleanField(default=True)),
                ('generalNoti', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_noti_reception',
                'managed': True,
            },
        ),
    ]
