# Generated by Django 3.2.8 on 2022-04-17 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_usernotireception'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usernotireception',
            old_name='activityLevelUpNoti',
            new_name='activity_level_up',
        ),
        migrations.RenameField(
            model_name='usernotireception',
            old_name='dailyExerciseCompleteNoti',
            new_name='daily_exercise_complete',
        ),
        migrations.RenameField(
            model_name='usernotireception',
            old_name='exerciseAttendanceNoti',
            new_name='exercise_attendance',
        ),
        migrations.RenameField(
            model_name='usernotireception',
            old_name='generalNoti',
            new_name='general',
        ),
        migrations.RenameField(
            model_name='usernotireception',
            old_name='hotPostNoti',
            new_name='hot_post',
        ),
        migrations.RenameField(
            model_name='usernotireception',
            old_name='hotQnaNoti',
            new_name='hot_qna',
        ),
        migrations.RenameField(
            model_name='usernotireception',
            old_name='postCommentNoti',
            new_name='post_comment_noti',
        ),
        migrations.RenameField(
            model_name='usernotireception',
            old_name='postReplyNoti',
            new_name='post_eply',
        ),
        migrations.RenameField(
            model_name='usernotireception',
            old_name='qnaAnswerNoti',
            new_name='qna_answer',
        ),
        migrations.RenameField(
            model_name='usernotireception',
            old_name='qnaBestAnswerNoti',
            new_name='qna_best_answer',
        ),
        migrations.RenameField(
            model_name='usernotireception',
            old_name='qnaCommentNoti',
            new_name='qna_comment',
        ),
        migrations.RenameField(
            model_name='usernotireception',
            old_name='qnaReplyNoti',
            new_name='qna_reply',
        ),
        migrations.RenameField(
            model_name='usernotireception',
            old_name='qnaSelectedAnswerNoti',
            new_name='qna_selected_answer',
        ),
        migrations.RenameField(
            model_name='usernotireception',
            old_name='weeklyExerciseProteinNoti',
            new_name='weekly_exercise_protein',
        ),
    ]
